# Generated by Django 3.2.16 on 2023-01-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stocks',
            new_name='stock',
        ),
    ]
